import { useState, useEffect } from 'react';
import { GardenState, PlantType, GardenTile, UserProfile } from '@/types/garden';

// Mock Data
// Mock Data
// TODO: Place real textures in /public/textures generated by AI as requested.
// Each asset_path below expects a PNG in that folder.
const MOCK_PLANT_TYPES: PlantType[] = [
    {
        id: 1,
        name: 'Brote de Calma',
        description: 'El inicio de todo gran jardín.',
        base_cost: 0,
        min_streak_required: 0,
        stage_required: 1,
        category: 'flower',
        sprite_key: '🌱',
        asset_path: '/garden/brote-calma.png'
    },
    {
        id: 2,
        name: 'Arbusto Frondoso',
        description: 'Verde y lleno de vida.',
        base_cost: 50,
        min_streak_required: 2,
        stage_required: 1,
        category: 'flower',
        sprite_key: '🌳',
        asset_path: '/garden/arbusto-frondoso.png'
    },
    {
        id: 3,
        name: 'Girasol Radiante',
        description: 'Sigue la luz de tu positividad.',
        base_cost: 80,
        min_streak_required: 3,
        stage_required: 2,
        category: 'flower',
        sprite_key: '🌻',
        asset_path: '/garden/girasol-radiante.png'
    },
    {
        id: 4,
        name: 'Cerezo Sakura',
        description: 'Mágico y rosado.',
        base_cost: 300,
        min_streak_required: 5,
        stage_required: 3,
        category: 'tree',
        sprite_key: '🌸',
        asset_path: '/garden/cerezo-sakura.png'
    },
    {
        id: 5,
        name: 'Pino Invernal',
        description: 'Resiste cualquier frío.',
        base_cost: 150,
        min_streak_required: 4,
        stage_required: 4,
        category: 'tree',
        sprite_key: '🌲',
        asset_path: '/garden/pino-invernal.png'
    },
    {
        id: 6,
        name: 'Cristal de Hielo',
        description: 'Decoración brillante.',
        base_cost: 200,
        min_streak_required: 5,
        stage_required: 4,
        category: 'decoration',
        sprite_key: '❄️',
        asset_path: '/garden/cristal-hielo.png'
    }
];

const INITIAL_PROFILE: UserProfile = {
    user_id: 'mock-user',
    tokens: 500,
    streak_days: 12,
    current_stage: 3, // Default to a nice stage
};

export function useGarden() {
    const [state, setState] = useState<GardenState>({
        profile: INITIAL_PROFILE,
        tiles: [],
        plantTypes: MOCK_PLANT_TYPES,
        stage: INITIAL_PROFILE.current_stage
    });

    const [loading, setLoading] = useState(true);

    // Initialize
    useEffect(() => {
        const stored = localStorage.getItem('gardenState_v2');
        if (stored) {
            try {
                setState(JSON.parse(stored));
            } catch (e) {
                console.error("Error parsing stored garden state", e);
                // Fallback to initial seed if parse fails
                const initialTiles: GardenTile[] = [
                    { grid_x: 0, grid_y: 0, plant_type_id: 1, plant_type: MOCK_PLANT_TYPES[0] }
                ];
                setState(prev => ({ ...prev, tiles: initialTiles }));
            }
        } else {
            // Initial seed directly
            const initialTiles: GardenTile[] = [
                { grid_x: 0, grid_y: 0, plant_type_id: 1, plant_type: MOCK_PLANT_TYPES[0] }
            ];
            setState(prev => ({ ...prev, tiles: initialTiles }));
        }
        setLoading(false);
    }, []);

    const saveState = (newState: GardenState) => {
        setState(newState);
        localStorage.setItem('gardenState_v2', JSON.stringify(newState));
    };

    const buyPlant = async (plantTypeId: number) => {
        const plant = MOCK_PLANT_TYPES.find(p => p.id === plantTypeId);
        if (!plant) return false;

        if (state.profile.tokens >= plant.base_cost) {
            const newProfile = {
                ...state.profile,
                tokens: state.profile.tokens - plant.base_cost
            };
            // In this mock, we just deduct tokens. The user logic handles the rest.
            saveState({ ...state, profile: newProfile });
            return true;
        }
        return false;
    };

    const placePlant = async (plantTypeId: number, x: number, y: number) => {
        const plant = MOCK_PLANT_TYPES.find(p => p.id === plantTypeId);
        if (!plant) return false;

        // Check if tile occupied?
        const existingIndex = state.tiles.findIndex(t => t.grid_x === x && t.grid_y === y);
        const newTiles = [...state.tiles];

        const newTile: GardenTile = {
            grid_x: x,
            grid_y: y,
            plant_type_id: plantTypeId,
            plant_type: plant
        };

        if (existingIndex >= 0) {
            newTiles[existingIndex] = newTile;
        } else {
            newTiles.push(newTile);
        }

        saveState({ ...state, tiles: newTiles });
        return true;
    };

    return {
        gardenState: state,
        buyPlant,
        placePlant,
        loading
    };
}
